### PR TITLE
Fix #160, Profile/Cover image upload issue

### LINKED ISSUE #160: Profile Image/Cover Image upload failed

### PR DESCRIPTION
**Pull request by bxute**
This PR includes:
 - Cover image upload issue fixed
 - Some profile image was not uploading due to FileNotFoundException.(Fixed)

### CODE REVIEW

File: app/src/main/java/com/hapramp/ui/activity/ProfileEditActivity.java [hunk 1]
```diff
@@ -85,6 +86,7 @@
   private final int PROFILE_IMAGE_UID = 1203;
   private ImageRotationHandler imageRotationHandler;
   private Handler mHandler;
+  private int REQUEST_IMAGE_SELECTOR = 109;
```
Comment (singhpratyush) [inline app/src/main/java/com/hapramp/ui/activity/ProfileEditActivity.java]: What is this variable used for?

Comment (bxute) [reply app/src/main/java/com/hapramp/ui/activity/ProfileEditActivity.java]: I will remove it.
