### PR TITLE
Fix #154, add sync operation with interrupted progress bar while load…

### LINKED ISSUE #153: NullPointerException in PostCreateComponent
```
Caused by java.lang.NullPointerException
Attempt to invoke virtual method 'java.lang.String com.hapramp.steem.models.User.getProfile_image()' on a null object reference
```

### LINKED ISSUE #154: User profile sync is not reliable in app.
The app should have a reliable sync mechanism for user profiles.
This is causing a crash some time.

### PR DESCRIPTION
**Pull request by bxute**
Fix #153

### CODE REVIEW

File: app/src/main/java/com/hapramp/ui/activity/HomeActivity.java [hunk 1]
```diff
@@ -137,16 +142,14 @@ private void setupToolbar() {
...
-    Crashlytics.setString(CrashReporterKeys.UI_ACTION, "home init");
-    Crashlytics.setUserIdentifier(HaprampPreferenceManager.getInstance().getCurrentSteemUsername());
-    dataStore = new DataStore();
-    fragmentManager = getSupportFragmentManager();
-    homeFragment = new HomeFragment();
-    profileFragment = new ProfileFragment();
-    settingsFragment = new SettingsFragment();
-    earningFragment = new EarningFragment();
-    progressDialog = new ProgressDialog(this);
+  private void syncBasiInfo() {
```
Comment (aviaryan) [inline app/src/main/java/com/hapramp/ui/activity/HomeActivity.java]: typo in method name
